### ISSUE TITLE
Galeria

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#113]
Potrzebujemy jakąś galerię, aby zebrać publikowane w różnych miejscach zdjęcia warsztatowe. (Hostingingi, niekórych zdjęć już umarły...)

Najpewniej należy wykorzystać jakieś gotowe rozwiązanie, bo implementowanie czegoś tak popularnego jest bez sensu.

**Comment by krzys-h** [comment]
Zdziwię się jeśli nie istnieje jakiś gotowiec do Django bo galeria to jest taka rzecz która się nadaje na tutorial "mój pierwszy projekt w Django" :P

**Comment by cytadela8** [comment]
A, żebyś się nie zdziwił. Znalazienie czegoś dobrego pod Django stricte może być trudne. Ogólnie to ekosystem Django nie jest zbyt duży niestety...

**Comment by krzys-h** [comment]
Closed in #179

See #180 for continuation of this issue
