### ISSUE TITLE
Inserting images doesn't use upload endpoint

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#116]
Something got broken (probably when merging) and tinymc inlines (base64 encodes and puts into HTML) images instead of using upload endpoint.

**Comment by cytadela8** [comment]
![obraz](https://user-images.githubusercontent.com/3736271/76039265-c9203480-5f43-11ea-9f7f-aad46941f80c.png)

**Comment by krzys-h** [comment]
Interesting, this is the behaviour it falls back to if uploads are not configured...

**Comment by cytadela8** [comment]
`404 Not Found http://localhost:8000/static/tinymce/js/tinymce/plugins/media/plugin.min.js`
This might be closely related

**Comment by krzys-h** [comment]
Seems to still work for me.

One possible problem: image uploads do not work when creating a new article, as it doesn't have a name/slug assigned yet, which is used in the file path. I thought I told TinyMCE to disable uploads in that case, but maybe I didn't...?

**Comment by krzys-h** [comment]
Well, I did disable automatic uploads, but that doesn't stop you from adding images... they just won't be uploaded and will be stored as base64 instead :joy: This also happens in all editors where uploads are not allowed (profile, workshop proposal etc)
