### ISSUE TITLE
Article container overlapped on small screens

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#117]
![obraz](https://user-images.githubusercontent.com/3736271/76039416-451a7c80-5f44-11ea-87b7-53fd3b58c180.png)
On smarthpone size screens article container is partially covered by navbar

**Comment by krzys-h** [comment]
The logo seems misplaced, causing the navbar to grow... it's supposed to be like this:
![Screenshot_20200306-015020_Chrome](https://user-images.githubusercontent.com/1517255/76039509-f2918e00-5f4c-11ea-89d9-085ea23866a8.jpg)

Does the currently deployed version break like that too for you?

**Comment by cytadela8** [comment]
YEP
![obraz](https://user-images.githubusercontent.com/3736271/76040113-654b3b00-5f46-11ea-8b2c-34db43894d37.png)

**Comment by cytadela8** [comment]
This is imp-low. It would be nice to fix, but not necessery

**Comment by cytadela8** [comment]
Breaks on Firefox IPhone 6/7/8 setting of 375x667
