### ISSUE TITLE
DatePicker in profile details page default month

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#131]
DatePicker default to current month in profile details page. It should default to a month with workshops.

**Comment by krzys-h** [comment]
It doesn't seem to do that for me? It has `data-default-date` set, and it does put this date in the text field when no date is set.

**Comment by cytadela8** [comment]
The issue is when a date is already set, becouse you have a date from last year.

**Comment by krzys-h** [comment]
What would you like it to do instead? Revert to defaults if the date is outside the allowed range? That would make it seem like the date is already set correctly, while in the database and participants view it isn't.

**Comment by cytadela8** [comment]
Maybe we should wipe the dates when we change editions?

**Comment by krzys-h** [comment]
Aren't we doing that already anyway? I though we cleared UserInfo objects between editions

**Comment by cytadela8** [comment]
I don't really like that it has any default at all, but I guess it's good enough for now.

Also when the UserInfo is not cleared user has to change to correct month manually and that's also not ideal. Let's leave it for now, but not close it as this requires revisiting.
