### ISSUE TITLE
Introduce Camp/Workshops model

### ISSUE THREAD

**Issue by gorbak25** [warsztatywww/aplikacjawww#151]
After so many editions(and two extra editions dubbed WWWX) it would be useful to introduce a Camp model so we can use this app for generic qualifications for any type of Camp/Workshop. This would remove the need of hard coding some settings and additionally would simplify some things.

**Comment by krzys-h** [comment]
Didn't we already have an issue for this?

Also, this is `size-big` because the code uses the year as a number in SO MANY PLACES

**Comment by grzegorz225** [comment]
@krzys-h I've looked at the issues and haven't found a similar issue.

**Comment by krzys-h** [comment]
Okay, so I guess it's "we discussed it may be useful but nobody made an issue for it"

**Comment by krzys-h** [comment]
The model for the workshop/camp edition should have:
* year, number, etc
* start/end date
* where does it take place
* qualification deadlines
* the plan: what workshops we had and at what days (mostly for historical purposes and statistics?)
* who was organizing this edition, who was the main organizer
* (obviously) links to workshops and participants

The articles should be reworked to pull this info from the database. Every year I find at least one place where we forgot to update the data...
