### ISSUE TITLE
Change address bar color on mobile to match our navigation bar

### ISSUE THREAD

**Issue by krzys-h** [warsztatywww/aplikacjawww#163]
I kinda like when websites do that, it makes them look well integrated

This can be done with
```html
<meta name="theme-color" content="#ff6600" />
```

Or for Apple devices apparently
```html
<meta name="apple-mobile-web-app-status-bar-style" content="black">
```

**Comment by krzys-h** [comment]
This is what it would look like (this is `#191919`)
![Screenshot_20200316-103318_Chrome](https://user-images.githubusercontent.com/1517255/76742597-9ced8a80-6771-11ea-87ed-6a9d8b84de5e.jpg)

**Comment by krzys-h** [comment]
Actually, forget Apple devices. The only supported values are `black`, `black-translucent` and `default`. They don't get to have nice things :stuck_out_tongue:

**Comment by cytadela8** [comment]
By the way. Maybe we should change the bar color to brown?

**Comment by cytadela8** [comment]
Our tshirts were always brown AFAIK

**Comment by krzys-h** [comment]
Maybe? I'm so used to the old navbar I can't tell if this is better or not
![Screenshot_20200316-114222_Chrome](https://user-images.githubusercontent.com/1517255/76748562-471de000-677b-11ea-9e02-ac8a785daf1b.jpg)

**Comment by krzys-h** [comment]
![image](https://user-images.githubusercontent.com/1517255/76748802-b0055800-677b-11ea-8908-ec20d546b1d6.png)
all of the blue accents on links etc. look slightly weird with this
