### ISSUE TITLE
"Błąd: Forbidden" when saving participant comment

### ISSUE THREAD

**Issue by MrQubo** [warsztatywww/aplikacjawww#170]
## To reproduce:
1. Type text into "Komentarz" field.
2. Click save button.

## Screenshot:
![image](https://user-images.githubusercontent.com/16545322/77019441-ccbead00-6980-11ea-9355-7aba1db73dab.png)

**Comment by krzys-h** [comment]
This is using the same `can_edit_workshop` function as all the other editors... I'll look at this tomorrow

**Comment by krzys-h** [comment]
Couldn't reproduce it on my local dev server. Is it possible this was caused by logging out in another tab or failed CSRF check?

**Comment by cytadela8** [comment]
Can't reproduce on prod server

**Comment by MrQubo** [comment]
Yeah, seems like CSRF in the cookie and header differ, I'll look into it.

**Comment by MrQubo** [comment]
Ok, I fixed this. Cookie and header still differ so assume it's intended.

The problem was missing Referer header. I've switched this preference (http://kb.mozillazine.org/Network.http.sendRefererHeader) from 2 to 1, by the description it should only affect loading images, seems like description is lacking some details.
