### ISSUE TITLE
Discrepancy between editor preview and final page

### ISSUE THREAD

**Issue by MrQubo** [warsztatywww/aplikacjawww#195]
There are some discrepancies between editor preview (Plik > Podgląd) and final page (Podgląd strony warsztatów).

Some tags, attributes and CSS properties are filtered out. Those are the ones I could find:
1. `<br/>` tag. It can be entered with Shift + Enter.
2. `target` and `rel` anchor attributes. It can be entered from the anchor edit menu.
3. `list-style-type` CSS property. There are some predefined bullet alternatives in the editor. More can be entered from source editor (Narzędzia > Kod źródłowy).

These things from the examples are saved on the server but not displayed on a workshop page.

### Possible fixes
1. Use the same filter as the editor. The editor itself uses some filtering when editing source code directly (Narzędzia > Kod źródłowy). We could use the same filter on server-side.
2. Improve the existing filter to not filter out things from the examples.

**Comment by MrQubo** [comment]
It seems like external `url()` links in CSS aren't allowed in the editor. I've added `url('http::/example.com/test')` url and it changed it to `url('/workshop/qiskit/edit/http::/example.com/test')`.

**Comment by cytadela8** [comment]
We should add more elements to our whitelist.
`br` and `list-style-type` definitely should be allowed. 
Security of `target` and `rel` should be checked as I don't know all context where those can be used.

**Comment by krzys-h** [comment]
1. is definitely the solution I would go for, but was too lazy to implement :shrug:

**Comment by cytadela8** [comment]
nah, I think we should just fix all found bugs with things that can be inputed without editing source, but are filtered out later.

**Comment by MrQubo** [comment]
@cytadela8 Do you have any other reasons except it being easier?

**Comment by MrQubo** [comment]
> 
> 
> nah, I think we should just fix all found bugs with things that can be inputed without editing source, but are filtered out later.

Do you have any other reasons except it being easier?

**Comment by cytadela8** [comment]
yes, the underlying problem is that our sanitization rules are too strict.

**Comment by MrQubo** [comment]
> yes, the underlying problem is that our sanitization rules are too strict.

That's what this issue is about. Using the same filter in the backend as in the frontend would completely fix this issue.

@cytadela8 
My question was why you don't like this forementioned solution.

**Comment by krzys-h** [comment]
I looked at the default sanitization rules in TinyMCE and they seem waaay to relaxed
https://github.com/tinymce/tinymce/blob/3e5f8a9c65009c4e68c7720670891dc38bdb8758/modules/tinymce/src/core/main/ts/api/html/Schema.ts#L126-L406

They are configurable though, so we can:
1. Add the things mentioned above to allowed elements
2. Reconfigure the TinyMCE sanitizer to be at least similar to the backend one
