### ISSUE TITLE
Transparent navigation header readability

### ISSUE THREAD

**Issue by MrQubo** [warsztatywww/aplikacjawww#196]
The navigation header is transparent which decreases readability.

<details>
<summary>Examples (click to expand)</summary>

Here navigation menu links blend with the page content.
![Screenshot_20200419_130928](https://user-images.githubusercontent.com/16545322/79686267-6e1a7680-823f-11ea-8c13-f54d67ad6334.png)

The blue color of „uczestnicy i ocenianie” suggests it's clickable, but it isn't.
![Screenshot_20200419_131617](https://user-images.githubusercontent.com/16545322/79686356-04e73300-8240-11ea-8b1c-67e065624b2d.png)

</details>

**Comment by cytadela8** [comment]
@krzys-h What do you think?

**Comment by MrQubo** [comment]
I propose disabling transparency on hover.

**Comment by MrQubo** [comment]
The navigation bar hides when scrolling down and appears when scrolling up. Why do you want to keep transparency?

**Comment by cytadela8** [comment]
I like transparency :P

**Comment by krzys-h** [comment]
I was never a fan of how the navbar behaves... but I just left it for now since we were planning a slight redesign for the next edition anyway

By the way, did you notice the navbar is LESS TRANSPARENT on mobile? :p

**Comment by MrQubo** [comment]
@cytadela8 
If you really want to keep it than I propose those changes:
- Remove autohiding of the navbar, it should be always visible.
- Decrease the height of the navbar, currently, it's taking quite a lot of space.
- Disable transparency on hover and when the view is on the top of the page (including some margin).
