### ISSUE TITLE
DataTables should be usable on mobile

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#201]
Current solution for tables (DataTables) is barely usable on mobile it's "responsivnes" frequently hides all columns by one. It's hard to sort by an column and see the same data as on desktop. Although sama data can't fit on smaller screen, previous non-responsive solution was more usable.

**Comment by krzys-h** [comment]
Moving to landscape mode and selecting only colums you care about usually helps, but I would prefer it to scroll horizontally rather than hide things as well.
