### ISSUE TITLE
Missing handling of AuthCanceled

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#227]
When OAuth fails for any reason (eg. user cancels) AuthCanceled exception is raised and not handled. It should be handled gracefully https://stackoverflow.com/questions/20907276/python-social-auth-authcanceled-exception

**Comment by cytadela8** [comment]
@gorbak25

**Comment by krzys-h** [comment]
https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#exceptions-middleware
