### ISSUE TITLE
Some photos are missing from gallery

### ISSUE THREAD

**Issue by krzys-h** [warsztatywww/aplikacjawww#249]
I messed up while downloading WWW12 and WWW13 photos from googke drive (ctrl+a selected only loaded and visible items not the entire directory...) so only the first 50 photos were uploaded to the site. We need to get more HDD space first though as I think we were running out, and fix the upload which broke somehow (#248)

Additionally, it would be nice to upload all photos from previous editions for archival purposes (the links to old ones are starting to die) and at least a screenshot or something from this year to maintain continuity.

**Comment by cytadela8** [comment]
Server has sufficient space now & upload is working.

**Comment by krzys-h** [comment]
I will probably upload the missing photos tomorrow then

**Comment by krzys-h** [comment]
I uploaded everything. I hope we still have some disk space left :P
