### ISSUE TITLE
Rework user details/questionnaires

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#260]
We ask users for different information each year. Currently we have some set of fields in profile including PESEL, address, t-shirt size, etc. This systems lacks following:

- [x] ability to easily change information requested (each year we might ask different information, changing code may be acceptable, but is not best)
- [x] we should not assume information inputted by user last year is still up-to-date. Currently we have no way for users to confirm that or to tell when it was filled in.
- [x] we should be able to lock changing forms, but locking everything at once is not acceptable (some information may be needed to lock earlier then other)
- [ ] there should be clear indication if user hasn't filled in some required information
- [ ] some forms should be accessible only to qualified users, some only to lecturers (not a blocker/not highest priority)

**Comment by krzys-h** [comment]
> we should not assume information inputted by user last year is still up-to-date

And some of it should not even be kept at all (like our privacy policy technically says). I'm pretty sure we used to remove/clear UserInfo objects between editions, but we no longer do for whatever reason (see also #152)

There also needs to be a better distinction between "things you need to fill out to apply" and "things you need to fill in after you are qualified". They are technically on different tabs of the profile, but there is nothing that explains the difference between them to end users. The "after qualification" tab should be inaccessible until you are actually qualified.

**Comment by cytadela8** [comment]
I think we can achieve indication "what you should fill in now" by locking. One thing I missed:
Some forms should be only accessible to qualified users. Some only to lecturers. Some to all.

**Comment by krzys-h** [comment]
See #291 and #292 for remaining points - the base forms system is now implemented
