### ISSUE TITLE
Add more Python code

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#267]
I see this
![obraz](https://user-images.githubusercontent.com/3736271/103388108-3585a900-4aff-11eb-8a69-0df596cbc550.png)
and I don't like it...

Also Github thinks this is a JavaScript project now...

**Comment by krzys-h** [comment]
This is mostly because of the libraries in https://github.com/warsztatywww/aplikacjawww/tree/master/static/js

**Comment by cytadela8** [comment]
We should not have libraries committed in repo...
