### ISSUE TITLE
Figure out why some of the old qual problems don't load after recent upload changes

### ISSUE THREAD

**Issue by krzys-h** [warsztatywww/aplikacjawww#357]
Seems to be something on nginx end (sentry doesn't report any issues)

See for example:
https://warsztatywww.pl/2020/workshop/filozofia_nauki1/qualProblems/
https://warsztatywww.pl/2015/workshop/torrent/qualProblems/

**Comment by krzys-h** [comment]
I can't see anything suspicious in the file URLs in the database in Django admin

**Comment by cytadela8** [comment]
Fixed, `chmod 644 *`
