### ISSUE TITLE
Article layout breaks on phone

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#389]
![Screenshot_20210306-184553.png](https://user-images.githubusercontent.com/3736271/110215870-4dd1c580-7eac-11eb-84b3-cfc173231274.png)

When article name doesnt fit in one line it should be miltiline

**Comment by krzys-h** [comment]
The same thing happens on my phone but it almost fits so it's barely noticeable. I'll see what I can do.
