### ISSUE TITLE
Rework participant list points popup

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#481]
- Remove solution comment in workshop participant list popup (or signifficantly limit shown length)
- Sort by points per cent received, non qualifing and not submitted should be on the bottom

**Comment by krzys-h** [comment]
> Remove solution comment in workshop participant list popup (or signifficantly limit shown length)

I think we should move the text comments to the profile page (#482) and remove them from here entirely. Now that the textbox is bigger lecturers are putting in way more text than before :P

> Sort by points per cent received, non qualifing and not submitted should be on the bottom

Just to be clear, you are talking about sorting the workshops inside the popup right?
