### ISSUE TITLE
Add submission result to profile page

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#482]
Add a simillar (or identical) table to the one from private "qualification" page on profile page.

Users with see_all_participant_data (or whatever it was called) permission should only see it above the motivation letter.

![obraz](https://user-images.githubusercontent.com/3736271/120078280-3f0b4100-c09e-11eb-9ffc-f613a435fe90.png)

**Comment by krzys-h** [comment]
> Users with see_all_participant_data (or whatever it was called) permission should only see it above the motivation letter.

Wait, doesn't `see_all_users` currently control BOTH motivational letter and participants list with qualification results? And what do you mean by `only`?

I guess our permission system is slightly inconsistent in that regard... `see_all_workshops` was meant to control access to unlisted workshops, read-only access to workshop settings and per-workshop participants lists (with results), but we added all the results data into the participant list without a permission check...

Do we even have users who can see the people list but shouldn't see the workshop list though?
