### ISSUE TITLE
Improve performance of people list page

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#516]
Currently the performance is impacted negatively by form results being included. Consider on-demand loading of form results or improving the query(ies) performance.

This includes participant and lecturer pages.

**Comment by krzys-h** [comment]
On-demand loading is likely not needed, optimization of queries and performance of the weird column alignment code is.

**Comment by krzys-h** [comment]
Now that we don't show form results in the all people table the loading time seems normal.
