### ISSUE TITLE
AlphaNumericField is buggy and not used

### ISSUE THREAD

**Issue by enedil** [warsztatywww/aplikacjawww#61]
`AlphaNumericField` does not properly validate for alphanumeric characters only (the contition is true for any string from this list: `"^", "_", _"]", "a%", "a\xd4"`). I notice that the only place where it is currently used is the first migration. Can we somehow properly delete the class without failing migrations?

**Comment by krzys-h** [comment]
Nothing should break if you just replace `AlphaNumericField` with `CharField` (the base class) in migrations.
(source: https://stackoverflow.com/questions/35096871/removing-a-django-migration-that-depends-on-custom-field-from-an-old-module)

And while we're on the topic of fixing old migrations, I believe the only place the `django-annoying` dependency is used is in some old migration here: https://github.com/warsztatywww/aplikacjawww/blob/34d6e912ab3ef920e8d222aafa8fdea431abdad6/wwwapp/migrations/0047_auto_20160423_1531.py
