### ISSUE TITLE
Migration wwwapp.0054_auto_20190713_0313 error

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#77]
Error happens on PostgreSQL
```
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: "no_idea"
...
django.db.utils.DataError: invalid input syntax for type date: "no_idea"
```

**Comment by cytadela8** [comment]
We should change migration so "no-idea" is converted to Null

**Comment by cytadela8** [comment]
I fixed this by removing old field and creating new. Data is not really migrateable and we don't need it.

**Comment by krzys-h** [comment]
That's why the test setup was using postgresql as well, told you we would run into some database-dependent thing at some point :joy:
