### ISSUE TITLE
Search for user

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#88]
Add "search for user" functionality. Should be able to locate participants and lecturers. Useful for accessing contact information.

**Comment by krzys-h** [comment]
Soo basically you want the "people info" tab back, only this time implemented properly with DataTables search, filtering and everything?

Should it be split by year, or contain all users in the database?

**Comment by cytadela8** [comment]
I want an easy way to go from a name or email address to user profile. maybe this feature should be implemented in the admin panel? There are already multiple ways of searching and filtering there. One could just add a "go to profile" button.
