### ISSUE TITLE
Improve page loading times

### ISSUE THREAD

**Issue by krzys-h** [warsztatywww/aplikacjawww#96]
The page loading times seem kinda slow and the Google benchmark seems to confirm it: https://developers.google.com/speed/pagespeed/insights/?hl=pl&url=https%3A%2F%2Fwarsztatywww.pl%2F

There are a couple things that could be done to improve the situation:
1. Enable compression on the web server (we are downloading a few MB of JavaScript on every page load!)
2. Enable caching of static resources
3. Make sure we only load the JS that's needed - the PDF export feature of DataTables makes up for 75% of JavaScript loaded on EVERY page (!) - in both size (loading time) and parsing time, ping @grzegorz225
4. Either move all external CSS/JS to our server (like it's done with most things right now) or decide on one CDN - right now some code is coming from Google CDN, some from Cloudflare CDN and some from Bootstrap CDN

**Comment by krzys-h** [comment]
For DataTables dependency lazy loading, see https://github.com/DataTables/Buttons/issues/43#issuecomment-149306061

**Comment by cytadela8** [comment]
seems static files caching should be fixed in nginx ping: @zielmicha

**Comment by krzys-h** [comment]
Shouldn't be closed yet as we didn't configure caching and compression yet

**Comment by krzys-h** [comment]
It's way better now! We are hitting 100 (max) on PC and 88 on mobile on the Google benchmark. The only thing that can be reasonably improved now is adding the caching headers.

**Comment by grzegorz225** [comment]
... and enabling TLS 1.3 and HTTP 2.0

**Comment by krzys-h** [comment]
that's not going to make nearly as much of a difference... i'm talking about things we can do that actually matter :stuck_out_tongue:

**Comment by cytadela8** [comment]
Clearing milestone. Some improvements were done so it's "good enough" for now.
